#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Aug 15, 2019 12:53:27 AM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def card_click():
    print('SecondPage_support.card_click')
    sys.stdout.flush()

def cardpulldata():
    print('SecondPage_support.cardpulldata')
    sys.stdout.flush()

def cds_click():
    print('SecondPage_support.cds_click')
    sys.stdout.flush()

def deposit_click():
    print('SecondPage_support.deposit_click')
    sys.stdout.flush()

def loan_click():
    print('SecondPage_support.loan_click')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import SecondPage
    SecondPage.vp_start_gui()




